# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_func <- function(table) {
    .Call('_tim_test_func', PACKAGE = 'tim', table)
}

aggregate_orders_tbl_deprecated <- function(table) {
    .Call('_tim_aggregate_orders_tbl_deprecated', PACKAGE = 'tim', table)
}

aggregate_orders_tbl <- function(table) {
    .Call('_tim_aggregate_orders_tbl', PACKAGE = 'tim', table)
}

lee_ready_vector <- function(price, bidprice, askprice) {
    .Call('_tim_lee_ready_vector', PACKAGE = 'tim', price, bidprice, askprice)
}

nocb_1min_vector <- function(price, tradetime) {
    .Call('_tim_nocb_1min_vector', PACKAGE = 'tim', price, tradetime)
}

nocb_1min_dataframe <- function(price, tradetime) {
    .Call('_tim_nocb_1min_dataframe', PACKAGE = 'tim', price, tradetime)
}

nocb_5min_vector <- function(price, tradetime) {
    .Call('_tim_nocb_5min_vector', PACKAGE = 'tim', price, tradetime)
}

nocb_5min_dataframe <- function(price, tradetime) {
    .Call('_tim_nocb_5min_dataframe', PACKAGE = 'tim', price, tradetime)
}

