# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lee_ready_vector <- function(price, bidprice, askprice) {
    .Call('_tim_lee_ready_vector', PACKAGE = 'tim', price, bidprice, askprice)
}

rcpparma_hello_world <- function() {
    .Call('_tim_rcpparma_hello_world', PACKAGE = 'tim')
}

rcpparma_outerproduct <- function(x) {
    .Call('_tim_rcpparma_outerproduct', PACKAGE = 'tim', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_tim_rcpparma_innerproduct', PACKAGE = 'tim', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_tim_rcpparma_bothproducts', PACKAGE = 'tim', x)
}

